#Application
server:
  port: 8084
spring:
  application:
    name: MatchingService

  #Kafka Consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: matching-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: com.example.MatchingService.event.RideRequestedEvent
    #Kafka Producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

#Location Service URL
location:
  service:
    url: http://localhost:8080

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info